// Audits the LIVE schema snapshot, not the migration files.
//
// Lives in scripts/ but is run FROM THE REPO ROOT (node
// scripts/audit_live_schema.mjs), so every path below is relative to the
// root rather than to this file.
//
// Reads schema-snapshot.csv (produced by scripts/audit_schema.sql,
// which CI regenerates weekly). Every finding
// here is about the database as it actually is -- which is where the
// global leagues.name constraint was hiding while file-based audits kept
// reporting all clear.
import fs from 'fs';

const FILE = 'schema-snapshot.csv';
if (!fs.existsSync(FILE)) {
  console.log(`No ${FILE}. Run scripts/audit_schema.sql, or trigger the Schema snapshot workflow.`);
  console.log('FAILING rather than passing: an audit that cannot see the database');
  console.log('has not checked anything, and reporting success for that is how a');
  console.log('checker ends up trusted while covering nothing.');
  process.exit(1);
}

const rows = [];
{ // minimal CSV parse that survives quoted commas
  const text = fs.readFileSync(FILE, 'utf8');
  let cur = [], field = '', q = false;
  for (let i = 0; i < text.length; i++) {
    const c = text[i];
    if (q) {
      if (c === '"' && text[i+1] === '"') { field += '"'; i++; }
      else if (c === '"') q = false;
      else field += c;
    } else if (c === '"') q = true;
    else if (c === ',') { cur.push(field); field = ''; }
    else if (c === '\n') { cur.push(field.replace(/\r$/,'')); rows.push(cur); cur = []; field = ''; }
    else field += c;
  }
  if (field || cur.length) { cur.push(field); rows.push(cur); }
}
const [head, ...body] = rows;
const recs = body.filter(r => r.length >= 4)
  .map(r => ({ kind: r[0], object: r[1], detail: r[2], extra: r[3] }));

const get = k => recs.filter(r => r.kind === k);
const findings = [];

// 0. Does the snapshot contain what this audit needs to read?
//
// Every check below is a filter over `rows`. A kind that is absent
// produces an empty filter, an empty filter produces no findings, and no
// findings reads as a pass -- so a snapshot generated by an older
// scripts/audit_schema.sql makes this whole file quietly meaningless.
//
// That has now happened twice: triggers were missing and read as absent
// from the database, and the security-definer flag was missing and read
// as zero definers. Both passed review. Checking up front is cheaper than
// discovering the third one the same way.
{
  const EXPECTED = ['column', 'constraint', 'function', 'index', 'policy', 'rls', 'trigger', 'grant'];
  const present = new Set(recs.map(r => r.kind));
  const absent = EXPECTED.filter(k => !present.has(k));
  if (absent.length) {
    findings.push(
      `AUDIT BLIND: the snapshot has no ${absent.join(', ')} rows. Every check `
      + `over ${absent.length === 1 ? 'that kind' : 'those kinds'} will pass by `
      + `default. Regenerate with the current scripts/audit_schema.sql.`);
  }
}
const shared = [];   // global-name constraints that are correct by design
const seenUnique = new Set();
const intentionalLockouts = [];

// 1. RLS disabled anywhere.
for (const r of get('rls')) {
  if (r.detail === 'DISABLED') findings.push(`RLS DISABLED on ${r.object}`);
}

// 2. Unique constraints that are NOT scoped to an owner.
//
// This is the leagues bug generalised: a unique index on a user-facing
// name with no user column makes that name a global namespace, so the
// second user to want it gets 23505 and their data never syncs.
const OWNER_COLS = ['user_id','created_by','owner_id','bowler_id','coach_id'];
for (const r of [...get('constraint'), ...get('index')]) {
  const def = r.extra || '';
  const isUnique = /UNIQUE/i.test(def) || /CREATE UNIQUE/i.test(def);
  if (!isUnique) continue;
  if (/_pkey/.test(r.detail)) continue;
  if (seenUnique.has(`${r.object}.${r.detail}`)) continue;
  seenUnique.add(`${r.object}.${r.detail}`);
  const mentionsOwner = OWNER_COLS.some(c => def.includes(c));
  const looksLikeName = /\bname\b|\btitle\b|\bemail\b/i.test(def);
  if (!looksLikeName || mentionsOwner) continue;

  // A SHARED CATALOG legitimately has one row per name -- oil_patterns
  // is meant to be one "Chameleon" for everyone, not one per bowler.
  // The tell is a read policy open to every signed-in user rather than
  // scoped to a row owner.
  const readPolicies = get('policy').filter(p => p.object === r.object && /SELECT/i.test(p.extra));
  const isSharedCatalog = readPolicies.some(p => /auth\.uid\(\) IS NOT NULL/i.test(p.extra));
  if (isSharedCatalog) {
    shared.push(`${r.object}.${r.detail} (shared catalog -- global name is intended)`);
    continue;
  }
  findings.push(`GLOBAL unique on a name: ${r.object}.${r.detail} -> ${def.slice(0,80)}`);
}

// 3. Security definer functions -- not wrong, but each one bypasses RLS
//    and deserves to be a deliberate choice rather than a surprise.
//
//    This tested `extra === 'security definer'` against a field holding
//    the RETURN TYPE, so it matched nothing and reported all clear
//    forever. The snapshot now appends the prosecdef flag to that field,
//    and this looks for it rather than demanding the whole field be it.
const definers = get('function').filter(f => /security definer/.test(f.extra || ''));

//    Fail loudly if the snapshot predates the fix, rather than quietly
//    going back to reporting zero. A snapshot where NO function says
//    either way cannot answer the question, and its silence means
//    nothing -- which is exactly how this check went unnoticed.
const definerFlagged = get('function').filter(f => /security (definer|invoker)/.test(f.extra || ''));
if (get('function').length && !definerFlagged.length) {
  findings.push(
    'AUDIT BLIND: the snapshot records no security-definer flag on any function. '
    + 'Regenerate it with the current scripts/audit_schema.sql -- until then this '
    + 'check cannot see definers and its silence means nothing.');
}

// 3b. Tables whose UPDATE privilege was deliberately narrowed to specific
//     columns, and must stay that way.
//
//     These are a security control in their own right: RLS decides WHICH
//     ROWS, and these decide WHICH COLUMNS. A migration that re-granted
//     UPDATE on the whole table would reopen the hole with every policy
//     still looking correct, because no policy would have changed.
//
//     Both entries below were live exposures found in review -- a
//     teammate could rewrite whose roster row was whose, and whose
//     imported scores were whose.
const NARROWED = {
  team_members: ['is_sub', 'left_handed', 'lineup_position'],
  imported_scores: ['corrected_by', 'corrected_scores', 'corrected_shots',
                    'note', 'responded_at', 'status'],
};
{
  const grants = get('grant').filter(g => g.detail === 'UPDATE');
  if (!grants.length) {
    // Deliberately silent: check 0 above already reports that the
    // snapshot has no grant rows at all. Two findings for one cause
    // trains people to skim the list, which is how the real one gets
    // missed.
  } else {
    for (const [table, expected] of Object.entries(NARROWED)) {
      const row = grants.find(g => g.object === table);
      if (!row) {
        findings.push(`${table}: no UPDATE grant to authenticated at all -- `
          + `expected exactly ${expected.join(', ')}. Roster or correction `
          + `writes will be failing.`);
        continue;
      }
      const actual = String(row.extra || '').split(',').map(c => c.trim()).filter(Boolean).sort();
      const extra = actual.filter(c => !expected.includes(c));
      const missing = expected.filter(c => !actual.includes(c));
      if (extra.length) {
        findings.push(`${table}: UPDATE granted on ${extra.join(', ')} -- wider `
          + `than intended. This is how the original exposure reopens.`);
      }
      if (missing.length) {
        findings.push(`${table}: UPDATE missing on ${missing.join(', ')} -- `
          + `legitimate writes to those columns will be denied.`);
      }
    }
  }
}

// 4. Tables with RLS on but no policy at all.
const policied = new Set(get('policy').map(p => p.object));
for (const r of get('rls')) {
  if (r.detail === 'enabled' && !policied.has(r.object)) {
    // No policy AND no grant is a deliberate lockout: the table is
    // written only by a security definer function. api_usage is exactly
    // that -- letting a user touch their own rate-limit rows would let
    // them clear their own limit.
    intentionalLockouts.push(`${r.object} (no policy, no grant -- definer-only by design)`);
  }
}

// Tables in the database that no migration in this repo creates. Not a
// vulnerability, but every file-based audit is blind to them -- which is
// how a global unique on leagues.name passed several "all clear" reviews.
//
// This read every .sql at the repo root -- including schema.sql, which is
// GENERATED FROM THE LIVE DATABASE. A file listing every live table means
// no table can ever look undocumented, so the check reported all clear by
// construction. It was treating a snapshot of production as if it were
// migration history.
//
// It now reads supabase/migrations/ only: files somebody wrote, not files
// exported from the thing being audited.
{
  const MIGRATIONS = 'supabase/migrations';
  let files = [];
  try {
    files = fs.readdirSync(MIGRATIONS).filter(f => f.endsWith('.sql'))
      .map(f => `${MIGRATIONS}/${f}`);
  } catch { files = []; }

  if (!files.length) {
    // Saying nothing here would repeat the original bug in a new form:
    // an empty migrations directory produces an empty "in repo" set,
    // every table looks undocumented, and the wall of output would be
    // read as noise and ignored.
    console.log(`No migrations in ${MIGRATIONS}/ -- this repo cannot rebuild the database`);
    console.log('from source, and this check has nothing to compare against.');
    console.log(`The live schema has ${get('rls').length} tables; none of them are covered.`);
    console.log();
  } else {
    const sqlText = files.map(f => fs.readFileSync(f, 'utf8')).join('\n');
    const inRepo = new Set([...sqlText.matchAll(/create table if not exists public\.(\w+)/gi)].map(m => m[1]));
    const undocumented = get('rls').map(r => r.object).filter(t => !inRepo.has(t)).sort();
    if (undocumented.length) {
      console.log(`${undocumented.length} table(s) exist in the database but in NO migration here.`);
      console.log('This repo cannot rebuild them, and file-based audits cannot see them:');
      console.log('   ' + undocumented.join(', '));
      console.log();
    }
  }
}

console.log(`Snapshot: ${get('column').length} columns, ${get('rls').length} tables, ${get('policy').length} policies, ${get('function').length} functions.\n`);
console.log(`Security definer functions (${definers.length}) -- each bypasses RLS by design:`);
definers.forEach(f => console.log(`   ${f.object}(${f.detail})`));
console.log();
if (intentionalLockouts.length) {
  console.log(`Definer-only tables (${intentionalLockouts.length}):`);
  intentionalLockouts.forEach(x => console.log(`   ${x}`));
  console.log();
}
if (shared.length) {
  console.log(`Shared catalogs with intentional global names (${shared.length}):`);
  shared.forEach(x => console.log(`   ${x}`));
  console.log();
}
// Exits non-zero on a finding, so CI can actually stop on one.
//
// This ran as a CI step and always exited 0 -- it printed its findings
// and the build went green regardless. A step that cannot fail is
// decoration: it looks like coverage, and the first time it matters
// nobody notices.
//
// A finding here is narrow and serious: RLS switched off on a table, or
// a globally-unique constraint on a NAME column (which is how one
// bowler naming a league stops every other bowler using that name).
// Neither is a style preference; both are worth a red build.
//
// Note what is deliberately NOT a finding: tables that exist in the
// database but in no migration. That is real and worth fixing, but it is
// a backlog of 30, and failing on it would mean CI is red until that
// work is done -- at which point the gate gets removed rather than the
// problem fixed.
if (!findings.length) {
  console.log('No findings.');
  process.exit(0);
}
console.log(`${findings.length} finding(s):`);
findings.forEach(f => console.log(`   ${f}`));
process.exit(1);
